### ISSUE TITLE
Can't install lxml

### ISSUE THREAD

**Issue by eoghanstafford** [qpython-android/qpython.org#140]
Is there a way to install lxml? I want to be able to use BeautifulSoup and it doesn't seem to work without it.

**Comment by riverfor** [comment]
Please install lxml-qpython from QPYPI.

**Comment by darecAdirondack** [comment]
okay, ive downloaded lxml-qpython and extracted the folder into site-packages. now how do i get the program to use it? i tried using my normal code and it said i need to install a parser. then i tried:

      soup = BeautifulSoup(response.content, 'lxml-qpython')

and still nothing. im not sure what to do here?

**Comment by caaarlos** [comment]
@darecAdirondack , have you solved your problem? Please, double check if you extracted the correct folder to site-packages.  Inside the extracted folder (**lxml-qpython-2.3.6**), there is another folder named **lxml**. You have to extract the folder **lxml** to site-packages instead of the folder **lxml-qpython-2.3.6**.

**Comment by caaarlos** [comment]
@riverfor, I downloaded this lxml version: [](http://qpypi.qpython.org:11000/simple/lxml-qpython/). Does that should work on qpython3? 
When I run my code I get this:

```
from lxml import etree
ImportError: dlopen failed: library "libpython2.7.0.so" not found.
``` 
Did I download a wrong lib version? If so, how can I find the right version?

**Comment by ChrisYeGX** [comment]
Do you solve your probelm? I have the same probelm.
